on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: otjake/actiontest@v0.1
        with:
          who-to-greet: 'Jake'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "Cum at ${{ steps.hello.outputs.time }}"